language: ruby
sudo: false
distro: trusty
bundler_args: --binstubs --standalone --without documentation debug
script: bin/rspec
rvm:
  - 2.4     # Always try testing against latest patch release
  - 2.4.0
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
