language: ruby
sudo: false
distro: trusty
bundler_args: --binstubs --standalone --without documentation debug
script: bin/rspec
rvm:
  - 2.3
  - 2.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
